#!/bin/bash
#PBS -N process_data
#PBS -l select=1:ncpus=64:mem=256gb
#PBS -l walltime=24:00:00

#PBS -j oe
#PBS -o /rds/general/user/as5023/home/Lunar_point_model/logs/process_data.log.pbs

eval "$(~/miniforge3/bin/conda shell.bash hook)"    # Load conda
conda activate IRP

start_time=$(date +%s)

# Navigate to the directory where the job was submitted
cd $PBS_O_WORKDIR

rm -rf ../data/CSVs/combined/*.csv

top -b -d 5 -u as5023 > /rds/general/user/as5023/home/Lunar_point_model/logs/top.log 2>&1 &
MON_PID=$!

vmstat 5 > /rds/general/user/as5023/home/Lunar_point_model/logs/vmstat.log 2>&1 &
VM_PID=$!

# Run the Python script
python ../../data_processing/process_data.py   --n_workers 64 \
                            --download_dir /rds/general/user/as5023/ephemeral/Lunar_pm/data/raw \
                            --save_dir /rds/general/user/as5023/ephemeral/Lunar_pm/data/CSVs/raw \
                            --interp_dir /rds/general/user/as5023/home/Lunar_point_model/data/CSVs/interpolated \
                            --combined_dir /rds/general/user/as5023/home/Lunar_point_model/data/CSVs/combined \
                            --plot_dir /rds/general/user/as5023/home/Lunar_point_model/data/plots

kill $MON_PID 2>/dev/null
kill $VM_PID 2>/dev/null

end_time=$(date +%s)

echo -e "\nJob finished on $(date)"

total_seconds=$((end_time - start_time))
total_minutes=$((total_seconds / 60))
remaining_seconds=$((total_seconds % 60))

echo "Total runtime: ${total_minutes} minutes and ${remaining_seconds} seconds"
