Traceback (most recent call last):
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/jobscripts/../compute_psrs.py", line 81, in <module>
    main(args)
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/jobscripts/../compute_psrs.py", line 36, in main
    elev_grid = load_and_prepare_data(args, sample=1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/utils/illum_conditions.py", line 21, in load_and_prepare_data
    df = load_csvs_parallel(args.upload_dir, args.n_workers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/utils/utils.py", line 25, in load_csvs_parallel
    csv_files = [f for f in os.listdir(directory) if f.endswith('.csv')]
                            ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../data/CSVs/combined'

Job finished on Fri  1 Nov 16:38:54 GMT 2024
Total runtime: 0 minutes and 31 seconds

====================================
CPU Time used: 00:00:00
CPU Percent: 0%
Memory usage: 0b
Approx Power usage: 0.0
Walltime usage: 00:00:42

====================================
