Processing LOLA data...
Processing Diviner data...
Processing M3 data...
Raw CSVs for MiniRF found at: /rds/general/user/as5023/ephemeral/data/CSVs/raw/Mini-RF. Skipping load df...
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/rds/general/user/as5023/home/miniforge3/envs/IRP/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/utils/load_dfs.py", line 125, in load_lro_df
    raise ValueError(f"No files found with extension '{lbl_ext}' in directory: {file_path}\nHave you downloaded the data?")
ValueError: No files found with extension '_jp2.lbl' in directory: /rds/general/user/as5023/ephemeral/data/raw/LOLA
Have you downloaded the data?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/jobscripts/../process_data.py", line 79, in <module>
    main(args)
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/jobscripts/../process_data.py", line 34, in main
    raise e
  File "/rds/general/user/as5023/home/Lunar_point_model/data_processing/jobscripts/../process_data.py", line 32, in main
    future.result()
  File "/rds/general/user/as5023/home/miniforge3/envs/IRP/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/as5023/home/miniforge3/envs/IRP/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
ValueError: No files found with extension '_jp2.lbl' in directory: /rds/general/user/as5023/ephemeral/data/raw/LOLA
Have you downloaded the data?

Job finished on Sun 19 Jan 09:06:27 GMT 2025
Total runtime: 0 minutes and 40 seconds

====================================
CPU Time used: 00:00:00
CPU Percent: 0%
Memory usage: 42304kb
Approx Power usage: 0.0
Walltime usage: 00:00:50

====================================
