Raw CSVs for MiniRF found at: /rds/general/user/as5023/ephemeral/data/CSVs/raw/Mini-RF. Skipping load df...
Raw CSVs for LOLA found at: /rds/general/user/as5023/ephemeral/data/CSVs/raw/LOLA. Skipping load df...
Raw CSVs for M3 found at: /rds/general/user/as5023/ephemeral/data/CSVs/raw/M3. Skipping load df...
Raw CSVs for Diviner found at: /rds/general/user/as5023/ephemeral/data/CSVs/raw/Diviner. Skipping load df...
Loading stage complete after 0.00 mins

Interpolated CSVs appear to exist for M3 data. Skipping interpolation.
Interpolated CSVs appear to exist for LOLA data. Skipping interpolation.
Interpolated CSVs appear to exist for Diviner data. Skipping interpolation.
Interpolated CSVs appear to exist for MiniRF data. Skipping interpolation.
Interpolation stage complete after 0.00 mins

Dataframes combined.
Taking the upper 3.37% of points from LOLA. Threshold = 0.37
LOLA - Clusters at 1: 442, Clusters at 2: 480, Total clusters: 923
Label plot saved to /rds/general/user/as5023/home/Lunar_point_model/data/plots/LOLA_label_plot.png for LOLA

Taking the top 0.51% of points from M3. Threshold = 1.25
M3 - Clusters at 1: 18608, Clusters at 2: 2439, Total clusters: 21087
Label plot saved to /rds/general/user/as5023/home/Lunar_point_model/data/plots/M3_label_plot.png for M3

Label counts:
Diviner label - 0: 45.84%
Diviner label - 1: 0.00%
Diviner label - 2: 54.16%
LOLA label - 0: 96.63%
LOLA label - 1: 0.03%
LOLA label - 2: 3.35%
M3 label - 0: 99.49%
M3 label - 1: 0.28%
M3 label - 2: 0.23%
MiniRF label - 0: 95.21%
MiniRF label - 1: 4.79%
MiniRF label - 2: 0.00%

Label proportions after combining:
Label
2    50.058603
0    42.496258
3     2.706545
4     2.363357
1     2.254655
5     0.095338
6     0.024415
7     0.000829
Name: proportion, dtype: float64
Plot saved to /rds/general/user/as5023/home/Lunar_point_model/data/plots
Dataframes labeled after 215.00 mins


Job finished on Fri 20 Dec 17:46:31 GMT 2024
Total runtime: 216 minutes and 30 seconds

====================================
CPU Time used: 03:42:12
CPU Percent: 398%
Memory usage: 386917304kb
Approx Power usage: 0.04440000000000001
Walltime usage: 03:36:40

====================================
