name: IRP
channels:
  - defaults
  - conda-forge
dependencies:
 - pip
 - ipython
 - jupyter
 - numpy
 - scipy
 - pip:
   - -r requirements.txt
variables:
  PYTHONPATH: "${PYTHONPATH}:/path/to/root/directory"