Skipping Diviner download as directory already exists
Downloading LOLA to /rds/general/user/as5023/ephemeral/Lunar_pm/data/raw/LOLA
Skipping M3 download as directory already exists
Skipping M3_loc download as directory already exists
Skipping Mini-RF download as directory already exists
Downloaded 4162 LOLA files out of 4162 found

Job finished on Thu 24 Apr 10:33:22 BST 2025
Total runtime: 27 minutes and 45 seconds

====================================
CPU Time used: 00:04:00
CPU Percent: 16%
Memory usage: 172784kb
Approx Power usage: 0.0008
Walltime usage: 00:27:56

====================================
