Raw CSVs for LOLA found at: /rds/general/user/as5023/ephemeral/Lunar_pm/data/CSVs/raw/LOLA. Skipping load df...
Raw CSVs for M3 found at: /rds/general/user/as5023/ephemeral/Lunar_pm/data/CSVs/raw/M3. Skipping load df...
Raw CSVs for Diviner found at: /rds/general/user/as5023/ephemeral/Lunar_pm/data/CSVs/raw/Diviner. Skipping load df...
Raw CSVs for MiniRF found at: /rds/general/user/as5023/ephemeral/Lunar_pm/data/CSVs/raw/Mini-RF. Skipping load df...
Loading stage complete after 0.00 mins

Interpolated CSVs appear to exist for LOLA data. Skipping interpolation.
Interpolated CSVs appear to exist for MiniRF data. Skipping interpolation.
Interpolated CSVs appear to exist for Diviner data. Skipping interpolation.
Interpolated CSVs appear to exist for M3 data. Skipping interpolation.
Interpolation stage complete after 0.00 mins

Dataframes combined successfully. Shape: (32790547, 7)

REMINDER: Skip if combined CSVs already exist commented out in label.py
Taking the top 2.64% of points from Diviner. Threshold = 110
Plot saved to Diviner_labeled.png
North pole LOLA threshold: 0.40 (4.77% of data)
Clustering LOLA pole - eps=350.00 m, min_cluster=5
LOLA - Clusters at 1: 20709, Clusters at 2: 14, Total clusters: 20723
South pole LOLA threshold: 0.43 (2.06% of data)
Clustering LOLA pole - eps=350.00 m, min_cluster=5
LOLA - Clusters at 1: 18300, Clusters at 2: 21, Total clusters: 18321
Plot saved to LOLA_labeled.png

North pole M3 threshold: 0.41 (9.02% of data)
Clustering M3 pole - eps=350.00 m, min_cluster=5
M3 - Clusters at 1: 21400, Clusters at 2: 154, Total clusters: 21554
South pole M3 threshold: 0.28 (5.66% of data)
Clustering M3 pole - eps=350.00 m, min_cluster=5
M3 - Clusters at 1: 17112, Clusters at 2: 166, Total clusters: 17278
Plot saved to M3_labeled.png


Taking the top 4.03% of points from MiniRF. Threshold = 1.20
Plot saved to MiniRF_labeled.png

Label counts:
Diviner label - 0:  97.36%
Diviner label - 1:   0.00%
Diviner label - 2:   2.64%
LOLA label - 0:  96.98%
LOLA label - 1:   2.48%
LOLA label - 2:   0.54%
M3 label - 0:  93.02%
M3 label - 1:   3.85%
M3 label - 2:   3.13%
MiniRF label - 0:  95.97%
MiniRF label - 1:   4.03%
MiniRF label - 2:   0.00%

Label proportions after combining:
Label
0    84.977850
1     9.110089
2     4.726588
4     0.613293
3     0.466897
5     0.057263
6     0.047029
7     0.000991
Name: proportion, dtype: float64

Total number of points: 32790547

Plot saved to Label_continuous.png
Len of df: 32790547, dtype of label: int8
Len of df_bin: 32790547, dtype of label: int64
Percentage of labels >= 3: 1.19%

Binary label proportions (label=3):
Label
0    98.814527
1     1.185473
Name: proportion, dtype: float64

Total number of points: 32790547
Plot saved to Label_binary.png
Dataframes labeled after 63.52 mins


Job finished on Thu  1 May 21:19:36 BST 2025
Total runtime: 64 minutes and 14 seconds

====================================
CPU Time used: 01:01:56
CPU Percent: 101%
Memory usage: 12596688kb
Approx Power usage: 0.012199999999999999
Walltime usage: 01:04:23

====================================
