Region  Number of points Non psr (%) psr (%) Lon min Lon max Lat min Lat max
 South          11414184      96.28%   3.72%   0.015 359.985 -89.994 -75.000
 North          11414184      96.77%   3.23%   0.015 359.985  75.000  89.994
 Total          22828368      96.53%   3.47%   0.015 359.985 -89.994  89.994

REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
Plot saved to psr_binary__raw.png
/rds/general/user/as5023/home/Lunar_point_model/jobscripts/pbs/../../data_processing/psr_test.py:457: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels(labels, rotation=45)
Original label distribution:
Label
0    84.652568
1     8.236437
2     5.628237
4     0.837323
3     0.508924
6     0.071900
5     0.063119
7     0.001491
Name: proportion, dtype: float64
Original psr distribution:
psr
0    96.525932
1     3.474068
Name: proportion, dtype: float64
USING dx,dy = 300.0 m
USING dx,dy = 300.0 m
Final label distribution:
Label
0    85.0
1     8.0
2     6.0
3     1.0
4     1.0
5     0.0
6     0.0
7     0.0
Name: proportion, dtype: float64

PSR mode distribution after merging PSR data:
psr
0.0    94.257944
1.0     5.721188
NaN     0.020868
Name: proportion, dtype: float64
REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
Plot saved to psr_binary__rasterised.png

Percentage of points which are PSRs:            5.72%
Percentage of psrs at NP:                       41.01%
Percentage of psrs at SP:                       58.99%

Percentage of points labelled >=2:              7.12%
Percentage of points labelled >=3:              1.48%
Percentage of points labelled >=4:              0.97%

Percentage of labels >=2 labeled as PSR:        36.04%
Percentage of labels >=3 labeled as PSR:        63.53%
Percentage of labels >=4 labeled as PSR:        76.32%

Percentage of each label which is a PSR:
Label = 0,  868681  points out of 27736621  are PSR  (3.13%)
Label = 1,  165788  points out of  2699060  are PSR  (6.14%)
Label = 2,  531354  points out of  1845331  are PSR  (28.79%)
Label = 3,   65164  points out of   166861  are PSR  (39.05%)
Label = 4,  205304  points out of   274548  are PSR  (74.78%)
Label = 5,   16019  points out of    20696  are PSR  (77.40%)
Label = 6,   21899  points out of    23575  are PSR  (92.89%)
Label = 7,     463  points out of      489  are PSR  (94.68%)

REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
Plot saved to Label_binary.png
Percentage of points with cat 0 (TN): 93.74%
Percentage of points with cat 1 (FN): 4.78%
Percentage of points with cat 2 (FP): 0.54%
Percentage of points with cat 3 (TP): 0.94%
REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
REMINDER: plotting only to 5° radius, not 15° - Change in set_axes()
Plot saved to class_category.png

PRECISION (How trustworthy is a positive value):        0.7934
RECALL (Portion of psrs with positive values):          0.5795
F1 SCORE (single-number trade-off between prec/rec):    0.6170
MCC (Correlation coefficient):                          0.3054
IOU (frac of union of detected ice and PSR common to both maps): 0.1505
Performance metrics not used: accuracy, acc_balanced, prec_weighted, rec_weighted, f1_weighted

Job finished on Wed 21 May 15:52:44 BST 2025
Total runtime: 20 minutes and 21 seconds

====================================
CPU Time used: 00:18:28
CPU Percent: 109%
Memory usage: 15367868kb
Approx Power usage: 0.0035999999999999995
Walltime usage: 00:20:31

====================================
