Region  Number of points Non psr (%) psr (%) Lon min Lon max Lat min Lat max
 South          11414184      96.28%   3.72%   0.015 359.985 -89.994 -75.000
 North          11414184      96.77%   3.23%   0.015 359.985  75.000  89.994
 Total          22828368      96.53%   3.47%   0.015 359.985 -89.994  89.994

Plot saved to psr_binary.png
Original label distribution:
Label
0    84.816518
1     8.258468
2     5.500769
4     0.803473
3     0.489398
6     0.069267
5     0.060686
7     0.001421
Name: proportion, dtype: float64
Projected combined_df_n to AEQD coordinates.
Projected combined_df_s to AEQD coordinates.
Projected psr_df_n to AEQD coordinates.
Projected psr_df_s to AEQD coordinates.
Average distance between points in combined_df_n: 611.1707
Average distance between points in combined_df_s: 611.1455
USING dx,dy = 300.0 m
USING dx,dy = 300.0 m
nearest PSR centroid : x   -454706.75
y   -454706.75
dtype: float32
cells with PSR value (south): 7223305

Label distribution after merging PSR data:
Label
0    84.811623
1     8.259128
2     5.504092
4     0.804003
3     0.489693
6     0.069313
5     0.060726
7     0.001422
Name: proportion, dtype: float64

PSR mode distribution after merging PSR data:
psr
0.0    94.258163
1.0     5.720970
NaN     0.020867
Name: proportion, dtype: float64
combined dx,dy : 300.0 300.0
min PSR spacing: (7.62939453125e-06, 7.62939453125e-06)
combined grid origin: -454800.06 -454800.06

Percentage of points which are PSRs:            5.72%
Percentage of psrs at NP:                       41.01%
Percentage of psrs at SP:                       58.99%

Percentage of points labelled >=2:              6.93%
Percentage of points labelled >=3:              1.43%
Percentage of points labelled >=4:              0.94%

Percentage of labels >=2 labeled as PSR:        36.11%
Percentage of labels >=3 labeled as PSR:        64.45%
Percentage of labels >=4 labeled as PSR:        77.74%

Percentage of each label which is a PSR:
Label = 0,  886139  points out of 27791646  are PSR  (3.19%)
Label = 1,  168601  points out of  2706407  are PSR  (6.23%)
Label = 2,  518982  points out of  1803618  are PSR  (28.77%)
Label = 3,   62655  points out of   160466  are PSR  (39.05%)
Label = 4,  200807  points out of   263461  are PSR  (76.22%)
Label = 5,   15729  points out of    19899  are PSR  (79.04%)
Label = 6,   21326  points out of    22713  are PSR  (93.89%)
Label = 7,     447  points out of      466  are PSR  (95.92%)

Plot saved to Label_binary.png
Percentage of points with cat 0: 93.77%
Percentage of points with cat 1: 4.80%
Percentage of points with cat 2: 0.51%
Percentage of points with cat 3: 0.92%
Plot saved to temp_category.png

Accuracy: 0.9469
Precision: 0.7979
Recall: 0.5776
F1 Score: 0.6148

Balanced Accuracy: 0.5776

Weighted Precision: 0.9337
Weighted Recall: 0.9469
Weighted F1 Score: 0.9315

Job finished on Sun  4 May 18:08:20 BST 2025
Total runtime: 23 minutes and 57 seconds

====================================
CPU Time used: 00:22:01
CPU Percent: 99%
Memory usage: 15344032kb
Approx Power usage: 0.004399999999999999
Walltime usage: 00:24:08

====================================
